version: '3.3'
services:
  ci_app:
    build:
      context: ./app
    restart: always
    ports:
      - '8010:80'
    volumes:
      - './app:/var/www/html'   
    depends_on:
      - db
    container_name: remark_web
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=db"    

  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "33061:3306"
    container_name: remark_db

volumes:
  dbdata: